### ISSUE TITLE
Please provide steps to use with AdMob and other plugins

### ISSUE THREAD

**Issue by jgberg** [floatinghotpot/cordova-mobfox-pro#19]
What steps are needed to install and use AdMob with this MobFox plugin?... This plugin installs admob i see, so can i just create an admob object and use your API?  Or do I need to install a plugin for it.  And for other ad networks that you support, how would I add that in... like for say inmobi?  Could you please detail what is needed to install and update one or more of your plugins that connect to other ad networks. 

Also could you provide some advice on how to choose between different ad networks.  As it is I use prepareInterstitial() to pre-fetch ads and then display them without causing the user to wait.  What if i do that across a number of ad networks?  Is it a bad idea when you have multiple ad networks?

Thanks.

**Comment by floatinghotpot** [comment]
hi jeffery, mobfox use admob library, so once mobfox installed, admob is installed too. you can install other ad plugins seperately like flurry, facebook audience network, etc. but do not install mopub as it conflicts with mobfox.

you can use multiple ad plugins, but avoid displaying them at the same time, and do not use too many as it will increase you package size.

it's recommended to call prepareInterstitial() with option autoShow:false, to load ad resource in background, then call show at best timing.

**Comment by jgberg** [comment]
Great... Got this working... Excellent
